url: http://panossakkos.github.io

# Site settings

title: "{ Panos Sakkos }"
description: "Panos Sakkos"
keywords: "panos, sakkos, panos sakkos, technology, computer science, Pwn Mail, WriteRight, UoA, di, CERN, MDCN, Microsoft"
google-tracking-id: UA-35880426-3

# Navigation bar links
# Blog link in the blog and post pages will point to the blog.html#blog
# In the default page it will point to the preview of the last post

pages_list:
  About: 'about'
  Blog: 'blog'
  Career: 'career'
  Contact: 'contact'

# Career variables

# Default career thumbnail image.
career-img: "img/timeline/default.jpg"

# Social networks variables (many more available: facebook, flickr, dribbble, pinterest, instagram, tumblr etc.)
social:
  - title: rss
    url: /feed.xml
  - title: github
    url: http://github.com/PanosSakkos
  - title: linkedin
    url: http://no.linkedin.com/in/PanosSakkos
  - title: youtube
    url: http://youtube.com/c/PanosSakkos
  - title: soundcloud
    url: https://soundcloud.com/psakkos/

# Exclusion list from the generated _site
exclude: ["Rakefile", "LICENSE", "readme.markdown"]
