
# Site settings

url: "https://tushar-maheshwari.github.io"
baseurl: ""
force-https: True

syntax-highlight: True

# Sections shown in the index page

pages_list:
  About: 'about'
  Publications: 'latest-post'
  Experiences: 'timeline'
  Projects: 'contact'
  

web-app-mode: True

# Icons for Chrome Web App mode https://developer.chrome.com/multidevice/android/installtohomescreen
icon-36p: "/img/web-app/icon-36p.png"
icon-48p: "/img/web-app/icon-48p.png"
icon-72p: "/img/web-app/icon-72p.png"
icon-96p: "/img/web-app/icon-96p.png"
icon-144p: "/img/web-app/icon-144p.png"
icon-192p: "/img/web-app/icon-192p.png"

#############
# HTML Head #
#############

author: "Tushar Maheshwari"
lang: "en"
title: "{ Tushar Maheshwari }"
short-title: "{ Tushar }"
favicon: "/img/black-lock.png"
description: "Undergraduate NLP Researcher"
keywords: ""
################
# Intro layout #
################

black-favicon: "/img/lock.png"
background-img: "../img/opera.jpg"
me-img: "/img/me.jpg"

##############################
# Color the browser elements #
##############################
color-browser: "#000000"
apple-status-bar-style: "black"

##############################
# Dynamic Text on the header #
##############################

dynamic-typing: True
shuffle: False # Shuffle the lines.
loop: False
loop-count: 1 # Set False for infinite loop, or set any number for finite loop.
type-speed: 4 # Default 10
start-delay: 2000 # Default 200
delete-delay: 50000 # Default 5000
lines: # You can add HTML Tags in the Text
  - text: "Undergraduate NLP Researcher"

########
# Blog #
########

enable-gesture-navigation: False

post-preview-words: 0

paginate: 5

email-share: True
fb-share: True
twitter-share: True
linkedin-share: True
reddit-share: True
google-plus-share: True
tumblr-share: True
pinterest-share: True
pocket-share: True
vkontakte-share: True

disqus-shortname: "Tushar"

###############
# Life Events #
###############

events:
  - image: "/img/career/ibm.png"
    date: "October 2016"
    description: " *'A Societal Sentiment Analysis: Predicting the Values and Ethics of Individuals by Analysing Social Media Content'* Awarded 2nd best poster  @ IBM I-CARE 2016 "
  - image: "/img/career/ntu.png"
    date: "Summer 2016"
    description: "Research Assistant @ Nanyang Technological University, under guidance of Professor Erik Cambria. Worked on *'Automatic Satire Detection'*"
  - image: "/img/career/iiith.png"
    date: "Summer 2015"
    description: "Design and development of Spy-Robot which using Wi-fi and Bluetooth communication networks and works on four control mechanisms i.e., DTMF, Remote, Speech, Gesture."
# First image of the Career timeline
#timeline-img: "/img/career/default.jpg"

##################
# Contact layout #
##################

email: "tushar.m14@iiits.in"

################
# Author Blurb #
################

# The author blurb goes underneath blog posts.
# This works best when your author blurb image has a transparent background, or matches your site background color.

# if the author_blurb is not set, then this feature is skipped
author_blurb: "I'm a junior undergraduate in IIIT-Sri City. I'm an NLP Enthusiast, and love to work of applied fields of Natural 
language processing. I am a part of the Natural Language processing Lab(HiLT) at IIIT-Sri City headed by Professor Amitava Das. We work on problems like Community
Detection, Social Media Analysis, Social Media Terrorism, Sentiment Analysis, Code-Mixing, Personality Detection, Values & Ethics Detection and
Figurative Language"
author_blurb_image: "/img/me.jpg"

##################
# Social Buttons
##################

social:
  - title: "github"
    url: "https://github.com/Tushar-Maheshwari"
  - title: "Facebook"
    url: "https://www.facebook.com/hitusharmaheshwari"  

############
# 404 page #
############

404-img: "/img/labtocat.png"

################################################################################

# Tread carefully if you want to change the variables bellow this point!

# Pagination path
#paginate_path: "blog/page:num"

# Enable minification SASS
sass:
  style: compressed

# Exclusion list from the generated _site
exclude: ["Rakefile", "LICENSE", "readme.markdown", "vendor", "scripts"]

gems:
  - jekyll-paginate
  - jemoji
