url: http://panossakkos.github.io

# Site Settings
title: Panos Sakkos
description: "Panos Sakkos"
keywords: "panos, sakkos, panos sakkos, MDCN, Pwn Mail, WriteRight, technology, computer science"
google-tracking-id: UA-35880426-3

# Navigation Bar Pages

pages_list:
  About: 'about'
  Blog: 'blog'
  Career: 'career'
  Contact: 'contact'

# Career Settings
# Default career thumbnail image.
career-img: "img/timeline/default.jpg"

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: rss
    url: /feed.xml
  - title: github
    url: http://github.com/PanosSakkos
  - title: linkedin
    url: http://no.linkedin.com/in/PanosSakkos
  - title: youtube
    url: http://youtube.com/c/PanosSakkos
  - title: soundcloud
    url: https://soundcloud.com/psakkos/

exclude: ["Rakefile", "LICENSE", "readme.markdown"]
