url: http://panossakkos.github.io

# Site Settings
title: Panos Sakkos
description: "Panos Sakkos"
keywords: "panos, sakkos, panos sakkos, MDCN, Pwn Mail, WriteRight, technology, computer science"
google-tracking-id: UA-35880426-3

# Career Settings
# Default career thumbnail image.
career-img: "img/timeline/default.jpg"

exclude: ["Rakefile", "LICENSE", "readme.markdown"]
